### PR TITLE
ci.yml Also run tests on windows-latest and macos-latest and fix platform specific build errors and warnings

### PR DESCRIPTION
**Pull request by kwinz**
Currently `rust-headless-chrome` developers mainly develop on Linux systems or don't have Windows systems to test on. Moreover the Github actions also don't run tests for the Windows platform.

Therefore `rust-headless-chrome` may release broken crates that affect Windows or MacOS systems and the bugs might go unnoticed for a release or two.

Such as happend recently in https://github.com/rust-headless-chrome/rust-headless-chrome/issues/427 or https://github.com/mdrokz/auto_generate_cdp/issues/12 And even when patching those it was hard to get the patch right, even when the build didn't even pass a simple compile.

This pull request ads `windows-latest` to `ci.yml`. This will increase build-minutes, but make it immediately obvious if there is a problem building `rust-headless-chrome` for Windows:

image

### CODE REVIEW

**Comment by kwinz** [comment]
PS: let me know if I should also include `macos-latest` in the tests.

**Comment by Billy-Sheppard** [comment]
Yes please.

**Comment by kwinz** [comment]
@Billy-Sheppard Done! Thank you for the feedback!

**Comment by kwinz** [comment]
@Billy-Sheppard Done! Thank you for the feedback!

**Comment by Billy-Sheppard** [comment]
https://github.com/kwinz/rust-headless-chrome-winfix/pull/1

Try merging this into your branch @kwinz

**Comment by kwinz** [comment]
Done! All tests are passing now.

**Comment by kwinz** [comment]
@Billy-Sheppard It didn't really help much, when 4 pull request that caused CI checks to fail were merged regardless.

And now somebody changed the workflow config without approving the new workflow file so tests are not being shown at all any more in the pull requests.

I can't send a pull request to fix this. Only maintiners can approve the new workflow on the github website.

And if maintiners are force-merging broken code failing the integration tests I also can't fix that.

**Comment by Billy-Sheppard** [comment]
Hi @kwinz - lets get this fixed, I'm not sure where I can `approve the new workflow file` but per PR a new contributor needs a maintainer to approve and run the CI for the first time.

I can see in your link there, there is a bunch of failed runs, but I don't see where to approve anything from your PR in November.

**Pull request merged**
