### PR TITLE
Added a method for adding manually opened tabs

### PR DESCRIPTION
**Pull request by Asthowen**
This PR adds a method for saving tabs that have been opened manually, the tabs are added to the right place in the list.

### CODE REVIEW

**Comment by Asthowen** [comment]
Hello, are you interested in this PR (to find out if it's useful for me to resolve conflicts or not)?

**Comment by mdrokz** [comment]
> Hello, are you interested in this PR (to find out if it's useful for me to resolve conflicts or not)?

Hi sorry for the late reply i will review this today can you resolve the conflicts ?

**Comment by Asthowen** [comment]
Hello, thanks for your quick reply, I've just resolved the conflicts.

**Comment by kwinz** [comment]
@mdrokz LGTM on a pull request where the tests failed (X next to commit id)?

**Comment by Asthowen** [comment]
It's not because of this PR that the tests are failing - they were failing before...

**Pull request merged**
